using System;
using NUnit.Framework;

namespace MyCode.Tests
{
    public class MyClassTests
    {
        [Test]
        public void FirstMethodTest()
        {
            Assert.Fail("Autogenerated");
        }

        [Test]
        public void SecondMethodTest()
        {
            Assert.Fail("Autogenerated");
        }

        [Test]
        public void ThirdMethodTest()
        {
            Assert.Fail("Autogenerated");
        }

        [Test]
        public void ThirdMethodTest()
        {
            Assert.Fail("Autogenerated");
        }

        [Test]
        public void NewMethodTestTest()
        {
            Assert.Fail("Autogenerated");
        }
    }
}